# Generated by Django 5.1.3 on 2024-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_name',
            field=models.CharField(default=None, max_length=225),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
