# Generated by Django 5.1.3 on 2024-12-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_content_name_alter_review_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_name',
        ),
    ]
